version: '3'

services:
  apache:
    image: httpd:2.4
    volumes:
      - ./:/var/www/html
      - ./docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php

  nginx:
    image: nginx:1.25.1
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apache

  php:
    image: php:8.1-fpm
    volumes:
      - ./:/var/www/html